stages:
  - dev-deploy
          
deploy:
  stage: dev-deploy
  only:
      - dev
  before_script:
      - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
      - eval $(ssh-agent -s)
      - echo "$_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - ssh-keyscan $_IP_ADDRESS >> ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no $_SERVER_USER@$_IP_ADDRESS "cd " $_DEPLOYMENT_PATH "; git stash; git pull origin development; composer install; php artisan config:cache; php artisan route:cache; php artisan cache:clear; sudo systemctl restart nginx"
